HW4:creature cyberdemon demon elf human balrog main
	g++ creature.o cyberdemon.o demon.o elf.o human.o balrog.o main.o -o HW4
creature:creature.cpp
	g++ -c creature.cpp -o creature.o
cyberdemon:cyberdemon.cpp
	g++ -c cyberdemon.cpp -o cyberdemon.o
demon:demon.cpp
	g++ -c demon.cpp -o demon.o
elf:elf.cpp
	g++ -c elf.cpp -o elf.o
human:human.cpp
	g++ -c human.cpp -o human.o
balrog:balrog.cpp
	g++ -c balrog.cpp -o balrog.o
main:main.cpp	
	g++ -c main.cpp -o main.o