program1:creditcardpayment payment cashpayment main 
	g++ creditcardpayment.o payment.o cashpayment.o main.o -o program1
creditcardpayment:creditcardpayment.cpp
	g++ -c creditcardpayment.cpp -o creditcardpayment.o
payment:payment.cpp
	g++ -c payment.cpp -o payment.o
cashpayment:cashpayment.cpp
	g++ -c cashpayment.cpp -o cashpayment.o
main:main.cpp
	g++ -c main.cpp -o main.o
