ps11:Ant Bug main Organism World
	g++ Ant.o Bug.o  main.o Organism.o World.o -o ps11
Ant:Ant.cpp
	g++ -c Ant.cpp -o Ant.o
Bug:Bug.cpp
	g++ -c Bug.cpp -o Bug.o
main:main.cpp
	g++ -c main.cpp -o main.o
Organism:Organism.cpp
	g++ -c Organism.cpp -o Organism.o
World:World.cpp
	g++ -c World.cpp -o World.o
